### ISSUE TITLE
Route to add friends

### ISSUE THREAD

**Issue by NTag** [jamjar919/sriracha#10]
The application will send with POST to the backend JSON like:
```json
[
  {
    "firstname": "Bob",
    "lastname": "Bidubou",
    "phoneNumbers": [
      "+4412345678",
      "0928377463",
      "+319482727288"
    ]
  }
]
```

**Comment by NTag** [comment]
Currently, the API only consider one phone number per friend, whereas there will be several.

**Comment by jamjar919** [comment]
current api spec is /api/:user/addfriend/

http POST username=something; name=friendname; phoneNumbers[]="01223893582"; phoneNumbers[]="07908102754";

**Comment by jamjar919** [comment]
i lied it's different

`  {
    "name": "john doe",
    "phoneNumbers": [
      "+4412345678",
      "0928377463",
      "+319482727288"
    ]
  }`

send that

**Comment by jamjar919** [comment]
#15
