### ISSUE TITLE
Add user - convert to json 

### ISSUE THREAD

**Issue by jamjar919** [jamjar919/sriracha#16]
Allow JSON post to the route `/api/adduser/` in the form:

    {
        username: "jjar",
        name:"James Paterson",
        "monzoid": "user_00009EvEunQCNeTDshAnWT"
    }

**Comment by NTag** [comment]
What you could do is, during the `monzo-connect`, you create a user associated with the `client_id` returned by Monzo, and then you pass the username to the app through the redirection.
