### ISSUE TITLE
Add a route /monzo-connect

### ISSUE THREAD

**Issue by NTag** [jamjar919/sriracha#4]
This GET route will receive a `code` query parameter containing the authorization code from Monzo (as described [here](https://monzo.com/docs/#acquire-an-access-token) **"Monzo redirects back to your app"**).

It will then exchange this authentication code for an access token with Monzo.

Finally, it will return a redirection to `helpmebudget://monzo-connect?access_token={here-the-access-token}`.

**Comment by thien** [comment]
@jamjar919

**Comment by jamjar919** [comment]
#8 #8

**Comment by jamjar919** [comment]
Can't test properly as need some valid auth-codes but this should be what you are looking for.

**Comment by NTag** [comment]
Seems to work :)!
